# This is a config for E2B sandbox template.
# You can use template ID (61kjt118n5mlnh5c00j9) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("61kjt118n5mlnh5c00j9") # Sync sandbox
# sandbox = await AsyncSandbox.create("61kjt118n5mlnh5c00j9") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('61kjt118n5mlnh5c00j9')

team_id = "856af4af-344e-44bf-9913-b8051c729c3f"
memory_mb = 4_098
cpu_count = 2
start_cmd = "/usr/local/bin/start-vnc.sh"
dockerfile = "e2b.Dockerfile"
template_id = "61kjt118n5mlnh5c00j9"
